### ISSUE TITLE
Идеи от простого смертного

### ISSUE THREAD

**Issue by FicusInAPot** [undrfined/TrappedChest#134]
Просьба не бить тапками если тупо пишете,что это тупо и т.д
1) Добавить возможность простым игрокам через @TrappedChestBot смотреть список игроков
2) Выпадение опыта на РД из кейсовхотя бы по 10%от левела и т.д(возможно плохая идея так как у донатеров будет большой левел ,но околки больно много стоят
3)сделать +одно оружия категории край чтоб были равные количество улучшений у каждой категории
4) осколки за каждый достиженный левел (т.е за 1 уровень 1,25-25 можно и больше
P.S.ваш любимый(нет) Фикус в горшке

**Comment by FicusInAPot** [comment]
Теги Хз как добавить,и писать такие идеи или это только для багов?

**Comment by undrfined** [comment]
1 готово, остальное нет и не будет(опыт уже был и его убрали из-за абуза донатерами уровней)

**Comment by FicusInAPot** [comment]
А как насчёт третьего не думаю ,что это связано с донатом
